### ISSUE TITLE
ManyToMany entities management

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-net-sample-app-template#5]
The current version of the Entity Framework Core does not support a Many To Many relation with an implicit (technical) join table. This table must be an explicit entity.

Let's take the example of the `Operation` and `Label` entity.  Thanks to Spring Data a Java Dev can simply define a collection of `Labels` in the `Operation` entity and a collection of `Operations` in the `Label` one. All the data piping is handle by the framework. 
With Entity Framework Core, an explicit `OperationLabel` entity must be declared. 
This constraints force JHipster.Net to :
* generate code to actually manage the relation (in which layer? service?)
* use Dtos By default for data exposition to mimic the Java Data objects.

**Comment by jdubois** [comment]
Adding a $100 bug bounty here as this is very important and very hard!
